server.port=${PORT:8081}

spring.application.name=dell-inventory

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/dell_inventory}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

amazon.base-url=${AMAZON_BASE_URL:http://localhost:8080}
amazon.sync-api-key=${SYNC_API_KEY}
inventory.api-key=${DELL_AMAZON_API_KEY}

dell.admin.username=${DELL_ADMIN_USER}
dell.admin.password=${DELL_ADMIN_PASSWORD}